version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/medusa
    environment:
      - POSTGRES_DB=medusa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ardpmsw22
    ports:
      - 5432:5432
volumes:
  postgres-db: